name: Production deploy

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
    builddeploy.front:
      name: Build and Deploy Front-end
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: highsoftware96/thebomb-frontend
          dockerfile: frontend/Dockerfile
          tags: latest
